//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class QLCUAHANGTHUCANNHANHEntities9 : DbContext
{
    public QLCUAHANGTHUCANNHANHEntities9()
        : base("name=QLCUAHANGTHUCANNHANHEntities9")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<CaLam> CaLams { get; set; }
    public virtual DbSet<ChamCong> ChamCongs { get; set; }
    public virtual DbSet<ChucDanh> ChucDanhs { get; set; }
    public virtual DbSet<DatHang> DatHangs { get; set; }
    public virtual DbSet<DoAn> DoAns { get; set; }
    public virtual DbSet<DonHang> DonHangs { get; set; }
    public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
    public virtual DbSet<KhachHang> KhachHangs { get; set; }
    public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
    public virtual DbSet<LoaiDoAn> LoaiDoAns { get; set; }
    public virtual DbSet<LoaiDonHang> LoaiDonHangs { get; set; }
    public virtual DbSet<LoaiHoaDon> LoaiHoaDons { get; set; }
    public virtual DbSet<LoaiKhuyenMai> LoaiKhuyenMais { get; set; }
    public virtual DbSet<LoaiNhanVien> LoaiNhanViens { get; set; }
    public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
    public virtual DbSet<MatHang> MatHangs { get; set; }
    public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
    public virtual DbSet<NhanVien> NhanViens { get; set; }
    public virtual DbSet<NhapKho> NhapKhoes { get; set; }
    public virtual DbSet<NuocUong> NuocUongs { get; set; }
    public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
    public virtual DbSet<PhucLoi> PhucLois { get; set; }
    public virtual DbSet<SanPham> SanPhams { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TaiKhoanNhanVien> TaiKhoanNhanViens { get; set; }
    public virtual DbSet<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
    public virtual DbSet<ThongTinThanhPhanDoAn> ThongTinThanhPhanDoAns { get; set; }
    public virtual DbSet<TraHang> TraHangs { get; set; }
    public virtual DbSet<ViPham> ViPhams { get; set; }
    public virtual DbSet<XuatKho> XuatKhoes { get; set; }
    public virtual DbSet<KhoBan> KhoBans { get; set; }
    public virtual DbSet<ThongTinHangTon> ThongTinHangTons { get; set; }

    public virtual ObjectResult<Nullable<System.DateTime>> check_date_TraHang(string maDatHang)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("check_date_TraHang", maDatHangParameter);
    }

    public virtual ObjectResult<check_DoAn_LoaiDoAn_Result> check_DoAn_LoaiDoAn(string maLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<check_DoAn_LoaiDoAn_Result>("check_DoAn_LoaiDoAn", maLoaiDoAnParameter);
    }

    public virtual ObjectResult<string> check_exist_NhanVien(string maNhanVien)
    {
        var maNhanVienParameter = maNhanVien != null ?
            new ObjectParameter("maNhanVien", maNhanVien) :
            new ObjectParameter("maNhanVien", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("check_exist_NhanVien", maNhanVienParameter);
    }

    public virtual ObjectResult<check_MaNhapKho_Result> check_MaNhapKho(string maNhap)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<check_MaNhapKho_Result>("check_MaNhapKho", maNhapParameter);
    }

    public virtual ObjectResult<check_MatHang_ThanhPhan_Result> check_MatHang_ThanhPhan(string maHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<check_MatHang_ThanhPhan_Result>("check_MatHang_ThanhPhan", maHangParameter);
    }

    public virtual ObjectResult<check_PhieuDat_PhieuNhap_Result> check_PhieuDat_PhieuNhap(string maDat)
    {
        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<check_PhieuDat_PhieuNhap_Result>("check_PhieuDat_PhieuNhap", maDatParameter);
    }

    public virtual ObjectResult<string> check_PhieuDat_PhieuTra(string maDat)
    {
        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("check_PhieuDat_PhieuTra", maDatParameter);
    }

    public virtual ObjectResult<Nullable<bool>> check_PhieuNhap(string maNhap)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("check_PhieuNhap", maNhapParameter);
    }

    public virtual ObjectResult<string> check_Quyen_DangNhap(string tenTaiKhoan)
    {
        var tenTaiKhoanParameter = tenTaiKhoan != null ?
            new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
            new ObjectParameter("tenTaiKhoan", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("check_Quyen_DangNhap", tenTaiKhoanParameter);
    }

    public virtual ObjectResult<chect_exist_LoaiDoAn_Result> chect_exist_LoaiDoAn(string maLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chect_exist_LoaiDoAn_Result>("chect_exist_LoaiDoAn", maLoaiDoAnParameter);
    }

    public virtual int create_tempThongTinNhapKho()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_tempThongTinNhapKho");
    }

    public virtual ObjectResult<DangNhap_Result> DangNhap(string tenTaiKhoan, string matKhau)
    {
        var tenTaiKhoanParameter = tenTaiKhoan != null ?
            new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
            new ObjectParameter("tenTaiKhoan", typeof(string));

        var matKhauParameter = matKhau != null ?
            new ObjectParameter("matKhau", matKhau) :
            new ObjectParameter("matKhau", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DangNhap_Result>("DangNhap", tenTaiKhoanParameter, matKhauParameter);
    }

    public virtual int delete_DatHang(string maDH)
    {
        var maDHParameter = maDH != null ?
            new ObjectParameter("maDH", maDH) :
            new ObjectParameter("maDH", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_DatHang", maDHParameter);
    }

    public virtual int delete_DoAn_ThanhPhanDoAn(string maThanhPhan, string maDoAn)
    {
        var maThanhPhanParameter = maThanhPhan != null ?
            new ObjectParameter("maThanhPhan", maThanhPhan) :
            new ObjectParameter("maThanhPhan", typeof(string));

        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_DoAn_ThanhPhanDoAn", maThanhPhanParameter, maDoAnParameter);
    }

    public virtual int delete_DoAn_ThongTinDoAn(string maDoAn)
    {
        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_DoAn_ThongTinDoAn", maDoAnParameter);
    }

    public virtual int delete_KhachHang(Nullable<int> idKhachHang)
    {
        var idKhachHangParameter = idKhachHang.HasValue ?
            new ObjectParameter("idKhachHang", idKhachHang) :
            new ObjectParameter("idKhachHang", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_KhachHang", idKhachHangParameter);
    }

    public virtual int delete_KM(string maKM)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_KM", maKMParameter);
    }

    public virtual int delete_LoaiDoAn(string maLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_LoaiDoAn", maLoaiDoAnParameter);
    }

    public virtual int delete_LoaiKM(string maLoai)
    {
        var maLoaiParameter = maLoai != null ?
            new ObjectParameter("maLoai", maLoai) :
            new ObjectParameter("maLoai", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_LoaiKM", maLoaiParameter);
    }

    public virtual int delete_MatHang(string maHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_MatHang", maHangParameter);
    }

    public virtual int delete_NhanVien(string maNhanVien)
    {
        var maNhanVienParameter = maNhanVien != null ?
            new ObjectParameter("maNhanVien", maNhanVien) :
            new ObjectParameter("maNhanVien", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_NhanVien", maNhanVienParameter);
    }

    public virtual int delete_PhieuNhap(string maNhap)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_PhieuNhap", maNhapParameter);
    }

    public virtual int delete_ThongTinDatHang(string maDatHang, string maHang)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_ThongTinDatHang", maDatHangParameter, maHangParameter);
    }

    public virtual int delete_ThongTinKhuyenMai(string maKM, string maSP)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        var maSPParameter = maSP != null ?
            new ObjectParameter("maSP", maSP) :
            new ObjectParameter("maSP", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_ThongTinKhuyenMai", maKMParameter, maSPParameter);
    }

    public virtual int delete_ThongTinTraHang(string maTra, string maHang)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_ThongTinTraHang", maTraParameter, maHangParameter);
    }

    public virtual int delete_to_NCC(string maNCC)
    {
        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_to_NCC", maNCCParameter);
    }

    public virtual int delete_to_NuocUong(string maNuocUong)
    {
        var maNuocUongParameter = maNuocUong != null ?
            new ObjectParameter("maNuocUong", maNuocUong) :
            new ObjectParameter("maNuocUong", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_to_NuocUong", maNuocUongParameter);
    }

    public virtual int delete_TraHang(string maTra)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_TraHang", maTraParameter);
    }

    public virtual int doi_MatKhau_TaiKhoanNhanVien(string tenTaiKhoan, string matKhauCu, string matKhauMoi)
    {
        var tenTaiKhoanParameter = tenTaiKhoan != null ?
            new ObjectParameter("tenTaiKhoan", tenTaiKhoan) :
            new ObjectParameter("tenTaiKhoan", typeof(string));

        var matKhauCuParameter = matKhauCu != null ?
            new ObjectParameter("matKhauCu", matKhauCu) :
            new ObjectParameter("matKhauCu", typeof(string));

        var matKhauMoiParameter = matKhauMoi != null ?
            new ObjectParameter("matKhauMoi", matKhauMoi) :
            new ObjectParameter("matKhauMoi", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("doi_MatKhau_TaiKhoanNhanVien", tenTaiKhoanParameter, matKhauCuParameter, matKhauMoiParameter);
    }

    public virtual ObjectResult<find_KhachHang_Result> find_KhachHang(string sDT)
    {
        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<find_KhachHang_Result>("find_KhachHang", sDTParameter);
    }

    public virtual int insert_DatHang(string maDH, Nullable<System.DateTime> ngayDat, Nullable<System.DateTime> ngaydukiengiao, string ghiChu, string phuongthucthanhtoan)
    {
        var maDHParameter = maDH != null ?
            new ObjectParameter("maDH", maDH) :
            new ObjectParameter("maDH", typeof(string));

        var ngayDatParameter = ngayDat.HasValue ?
            new ObjectParameter("ngayDat", ngayDat) :
            new ObjectParameter("ngayDat", typeof(System.DateTime));

        var ngaydukiengiaoParameter = ngaydukiengiao.HasValue ?
            new ObjectParameter("ngaydukiengiao", ngaydukiengiao) :
            new ObjectParameter("ngaydukiengiao", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var phuongthucthanhtoanParameter = phuongthucthanhtoan != null ?
            new ObjectParameter("phuongthucthanhtoan", phuongthucthanhtoan) :
            new ObjectParameter("phuongthucthanhtoan", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_DatHang", maDHParameter, ngayDatParameter, ngaydukiengiaoParameter, ghiChuParameter, phuongthucthanhtoanParameter);
    }

    public virtual int insert_DoAn_ThanhPhanDoAn(string maThanhPhan, string tenThanhPhan, string dinhLuong, string maDoAn, Nullable<int> soLuong)
    {
        var maThanhPhanParameter = maThanhPhan != null ?
            new ObjectParameter("maThanhPhan", maThanhPhan) :
            new ObjectParameter("maThanhPhan", typeof(string));

        var tenThanhPhanParameter = tenThanhPhan != null ?
            new ObjectParameter("tenThanhPhan", tenThanhPhan) :
            new ObjectParameter("tenThanhPhan", typeof(string));

        var dinhLuongParameter = dinhLuong != null ?
            new ObjectParameter("dinhLuong", dinhLuong) :
            new ObjectParameter("dinhLuong", typeof(string));

        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        var soLuongParameter = soLuong.HasValue ?
            new ObjectParameter("soLuong", soLuong) :
            new ObjectParameter("soLuong", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_DoAn_ThanhPhanDoAn", maThanhPhanParameter, tenThanhPhanParameter, dinhLuongParameter, maDoAnParameter, soLuongParameter);
    }

    public virtual int insert_DoAn_ThongTinDoAn(string maDoAn, string maLoaiDoAn, string tenDoAn, string donViBan, Nullable<decimal> donGia, string ghiChu)
    {
        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        var tenDoAnParameter = tenDoAn != null ?
            new ObjectParameter("tenDoAn", tenDoAn) :
            new ObjectParameter("tenDoAn", typeof(string));

        var donViBanParameter = donViBan != null ?
            new ObjectParameter("donViBan", donViBan) :
            new ObjectParameter("donViBan", typeof(string));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_DoAn_ThongTinDoAn", maDoAnParameter, maLoaiDoAnParameter, tenDoAnParameter, donViBanParameter, donGiaParameter, ghiChuParameter);
    }

    public virtual int insert_DonHang(string maDonHang, string tenDonHang, string maLoaiDon, string maHinhThuc, string maNhanVien, string sDTKhachHang, string maKhuyenMai, Nullable<System.DateTime> thoiGianDat, Nullable<int> trangThai, string ghiChu, Nullable<decimal> tongGia)
    {
        var maDonHangParameter = maDonHang != null ?
            new ObjectParameter("maDonHang", maDonHang) :
            new ObjectParameter("maDonHang", typeof(string));

        var tenDonHangParameter = tenDonHang != null ?
            new ObjectParameter("tenDonHang", tenDonHang) :
            new ObjectParameter("tenDonHang", typeof(string));

        var maLoaiDonParameter = maLoaiDon != null ?
            new ObjectParameter("maLoaiDon", maLoaiDon) :
            new ObjectParameter("maLoaiDon", typeof(string));

        var maHinhThucParameter = maHinhThuc != null ?
            new ObjectParameter("maHinhThuc", maHinhThuc) :
            new ObjectParameter("maHinhThuc", typeof(string));

        var maNhanVienParameter = maNhanVien != null ?
            new ObjectParameter("maNhanVien", maNhanVien) :
            new ObjectParameter("maNhanVien", typeof(string));

        var sDTKhachHangParameter = sDTKhachHang != null ?
            new ObjectParameter("SDTKhachHang", sDTKhachHang) :
            new ObjectParameter("SDTKhachHang", typeof(string));

        var maKhuyenMaiParameter = maKhuyenMai != null ?
            new ObjectParameter("maKhuyenMai", maKhuyenMai) :
            new ObjectParameter("maKhuyenMai", typeof(string));

        var thoiGianDatParameter = thoiGianDat.HasValue ?
            new ObjectParameter("thoiGianDat", thoiGianDat) :
            new ObjectParameter("thoiGianDat", typeof(System.DateTime));

        var trangThaiParameter = trangThai.HasValue ?
            new ObjectParameter("trangThai", trangThai) :
            new ObjectParameter("trangThai", typeof(int));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var tongGiaParameter = tongGia.HasValue ?
            new ObjectParameter("tongGia", tongGia) :
            new ObjectParameter("tongGia", typeof(decimal));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_DonHang", maDonHangParameter, tenDonHangParameter, maLoaiDonParameter, maHinhThucParameter, maNhanVienParameter, sDTKhachHangParameter, maKhuyenMaiParameter, thoiGianDatParameter, trangThaiParameter, ghiChuParameter, tongGiaParameter);
    }

    public virtual int insert_KM(string maKM, string tenKM, string maLoaiKM, Nullable<double> mucGiam)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        var tenKMParameter = tenKM != null ?
            new ObjectParameter("tenKM", tenKM) :
            new ObjectParameter("tenKM", typeof(string));

        var maLoaiKMParameter = maLoaiKM != null ?
            new ObjectParameter("maLoaiKM", maLoaiKM) :
            new ObjectParameter("maLoaiKM", typeof(string));

        var mucGiamParameter = mucGiam.HasValue ?
            new ObjectParameter("mucGiam", mucGiam) :
            new ObjectParameter("mucGiam", typeof(double));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_KM", maKMParameter, tenKMParameter, maLoaiKMParameter, mucGiamParameter);
    }

    public virtual int insert_LoaiDoAn(string maLoaiDoAn, string tenLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        var tenLoaiDoAnParameter = tenLoaiDoAn != null ?
            new ObjectParameter("tenLoaiDoAn", tenLoaiDoAn) :
            new ObjectParameter("tenLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_LoaiDoAn", maLoaiDoAnParameter, tenLoaiDoAnParameter);
    }

    public virtual int insert_LoaiKM(string maLoai, string tenLoai)
    {
        var maLoaiParameter = maLoai != null ?
            new ObjectParameter("maLoai", maLoai) :
            new ObjectParameter("maLoai", typeof(string));

        var tenLoaiParameter = tenLoai != null ?
            new ObjectParameter("tenLoai", tenLoai) :
            new ObjectParameter("tenLoai", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_LoaiKM", maLoaiParameter, tenLoaiParameter);
    }

    public virtual int insert_MatHang(string maHang, string tenHang, string maNCC, string donVi, Nullable<System.DateTime> nSX, Nullable<System.DateTime> hSD, Nullable<decimal> donGia, string ghiChu, Nullable<bool> loaiHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var tenHangParameter = tenHang != null ?
            new ObjectParameter("tenHang", tenHang) :
            new ObjectParameter("tenHang", typeof(string));

        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        var donViParameter = donVi != null ?
            new ObjectParameter("donVi", donVi) :
            new ObjectParameter("donVi", typeof(string));

        var nSXParameter = nSX.HasValue ?
            new ObjectParameter("NSX", nSX) :
            new ObjectParameter("NSX", typeof(System.DateTime));

        var hSDParameter = hSD.HasValue ?
            new ObjectParameter("HSD", hSD) :
            new ObjectParameter("HSD", typeof(System.DateTime));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var loaiHangParameter = loaiHang.HasValue ?
            new ObjectParameter("loaiHang", loaiHang) :
            new ObjectParameter("loaiHang", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_MatHang", maHangParameter, tenHangParameter, maNCCParameter, donViParameter, nSXParameter, hSDParameter, donGiaParameter, ghiChuParameter, loaiHangParameter);
    }

    public virtual int insert_NhanVien(string maNhanVien, string tenNhanVien, string phai, string sDT, string email, string diaChi, string maChucDanh, string maLoaiNhanVien)
    {
        var maNhanVienParameter = maNhanVien != null ?
            new ObjectParameter("maNhanVien", maNhanVien) :
            new ObjectParameter("maNhanVien", typeof(string));

        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("tenNhanVien", tenNhanVien) :
            new ObjectParameter("tenNhanVien", typeof(string));

        var phaiParameter = phai != null ?
            new ObjectParameter("Phai", phai) :
            new ObjectParameter("Phai", typeof(string));

        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));

        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));

        var diaChiParameter = diaChi != null ?
            new ObjectParameter("diaChi", diaChi) :
            new ObjectParameter("diaChi", typeof(string));

        var maChucDanhParameter = maChucDanh != null ?
            new ObjectParameter("maChucDanh", maChucDanh) :
            new ObjectParameter("maChucDanh", typeof(string));

        var maLoaiNhanVienParameter = maLoaiNhanVien != null ?
            new ObjectParameter("maLoaiNhanVien", maLoaiNhanVien) :
            new ObjectParameter("maLoaiNhanVien", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_NhanVien", maNhanVienParameter, tenNhanVienParameter, phaiParameter, sDTParameter, emailParameter, diaChiParameter, maChucDanhParameter, maLoaiNhanVienParameter);
    }

    public virtual int insert_NhapKho(string maNhap, Nullable<System.DateTime> ngayNhap, string maDat, string ghiChu)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        var ngayNhapParameter = ngayNhap.HasValue ?
            new ObjectParameter("ngayNhap", ngayNhap) :
            new ObjectParameter("ngayNhap", typeof(System.DateTime));

        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_NhapKho", maNhapParameter, ngayNhapParameter, maDatParameter, ghiChuParameter);
    }

    public virtual int insert_PhieuNhap(string maNhap, Nullable<System.DateTime> ngayNhap, string maDatHang, string ghiChu)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        var ngayNhapParameter = ngayNhap.HasValue ?
            new ObjectParameter("ngayNhap", ngayNhap) :
            new ObjectParameter("ngayNhap", typeof(System.DateTime));

        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_PhieuNhap", maNhapParameter, ngayNhapParameter, maDatHangParameter, ghiChuParameter);
    }

    public virtual int insert_ThongTinDatHang(string maDatHang, string maHang, Nullable<int> soLuongDat)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var soLuongDatParameter = soLuongDat.HasValue ?
            new ObjectParameter("soLuongDat", soLuongDat) :
            new ObjectParameter("soLuongDat", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ThongTinDatHang", maDatHangParameter, maHangParameter, soLuongDatParameter);
    }

    public virtual int insert_ThongTinDonHang(string maDonHang, string maSanPham, Nullable<decimal> giaTien, Nullable<int> soLuong, Nullable<decimal> thanhTien)
    {
        var maDonHangParameter = maDonHang != null ?
            new ObjectParameter("maDonHang", maDonHang) :
            new ObjectParameter("maDonHang", typeof(string));

        var maSanPhamParameter = maSanPham != null ?
            new ObjectParameter("maSanPham", maSanPham) :
            new ObjectParameter("maSanPham", typeof(string));

        var giaTienParameter = giaTien.HasValue ?
            new ObjectParameter("giaTien", giaTien) :
            new ObjectParameter("giaTien", typeof(decimal));

        var soLuongParameter = soLuong.HasValue ?
            new ObjectParameter("soLuong", soLuong) :
            new ObjectParameter("soLuong", typeof(int));

        var thanhTienParameter = thanhTien.HasValue ?
            new ObjectParameter("thanhTien", thanhTien) :
            new ObjectParameter("thanhTien", typeof(decimal));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ThongTinDonHang", maDonHangParameter, maSanPhamParameter, giaTienParameter, soLuongParameter, thanhTienParameter);
    }

    public virtual int insert_ThongTinKhuyenMai(string maKM, string maSP, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, string ghiChu)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        var maSPParameter = maSP != null ?
            new ObjectParameter("maSP", maSP) :
            new ObjectParameter("maSP", typeof(string));

        var ngayBDParameter = ngayBD.HasValue ?
            new ObjectParameter("ngayBD", ngayBD) :
            new ObjectParameter("ngayBD", typeof(System.DateTime));

        var ngayKTParameter = ngayKT.HasValue ?
            new ObjectParameter("ngayKT", ngayKT) :
            new ObjectParameter("ngayKT", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ThongTinKhuyenMai", maKMParameter, maSPParameter, ngayBDParameter, ngayKTParameter, ghiChuParameter);
    }

    public virtual int insert_ThongTinPhieuNhap(string maNhap, string maNCC, string maHang, Nullable<int> soLuong, Nullable<decimal> tongDonGia)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var soLuongParameter = soLuong.HasValue ?
            new ObjectParameter("soLuong", soLuong) :
            new ObjectParameter("soLuong", typeof(int));

        var tongDonGiaParameter = tongDonGia.HasValue ?
            new ObjectParameter("tongDonGia", tongDonGia) :
            new ObjectParameter("tongDonGia", typeof(decimal));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ThongTinPhieuNhap", maNhapParameter, maNCCParameter, maHangParameter, soLuongParameter, tongDonGiaParameter);
    }

    public virtual int insert_ThongTinTraHang(string maTra, string maHang, Nullable<int> soLuongTra)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var soLuongTraParameter = soLuongTra.HasValue ?
            new ObjectParameter("soLuongTra", soLuongTra) :
            new ObjectParameter("soLuongTra", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_ThongTinTraHang", maTraParameter, maHangParameter, soLuongTraParameter);
    }

    public virtual int insert_to_NCC(string maNCC, string tenNCC, string diachiNCC, string emailNCC, string sdtNCC, string ghiChu)
    {
        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        var tenNCCParameter = tenNCC != null ?
            new ObjectParameter("tenNCC", tenNCC) :
            new ObjectParameter("tenNCC", typeof(string));

        var diachiNCCParameter = diachiNCC != null ?
            new ObjectParameter("diachiNCC", diachiNCC) :
            new ObjectParameter("diachiNCC", typeof(string));

        var emailNCCParameter = emailNCC != null ?
            new ObjectParameter("emailNCC", emailNCC) :
            new ObjectParameter("emailNCC", typeof(string));

        var sdtNCCParameter = sdtNCC != null ?
            new ObjectParameter("sdtNCC", sdtNCC) :
            new ObjectParameter("sdtNCC", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_to_NCC", maNCCParameter, tenNCCParameter, diachiNCCParameter, emailNCCParameter, sdtNCCParameter, ghiChuParameter);
    }

    public virtual int insert_to_NuocUong(string maNuocUong, string tenNuocUong, string donViBan, Nullable<decimal> donGia)
    {
        var maNuocUongParameter = maNuocUong != null ?
            new ObjectParameter("maNuocUong", maNuocUong) :
            new ObjectParameter("maNuocUong", typeof(string));

        var tenNuocUongParameter = tenNuocUong != null ?
            new ObjectParameter("tenNuocUong", tenNuocUong) :
            new ObjectParameter("tenNuocUong", typeof(string));

        var donViBanParameter = donViBan != null ?
            new ObjectParameter("donViBan", donViBan) :
            new ObjectParameter("donViBan", typeof(string));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_to_NuocUong", maNuocUongParameter, tenNuocUongParameter, donViBanParameter, donGiaParameter);
    }

    public virtual int insert_TraHang(string maTra, Nullable<System.DateTime> ngayTra, string ghiChu, string maDat)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var ngayTraParameter = ngayTra.HasValue ?
            new ObjectParameter("ngayTra", ngayTra) :
            new ObjectParameter("ngayTra", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_TraHang", maTraParameter, ngayTraParameter, ghiChuParameter, maDatParameter);
    }

    public virtual int rs_mkTKNV(Nullable<int> id)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rs_mkTKNV", idParameter);
    }

    public virtual ObjectResult<select_ChucDanh_Result> select_ChucDanh()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ChucDanh_Result>("select_ChucDanh");
    }

    public virtual ObjectResult<select_DatHang_Result> select_DatHang()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_DatHang_Result>("select_DatHang");
    }

    public virtual ObjectResult<select_DoAn_ThanhPhanDoAn_Result> select_DoAn_ThanhPhanDoAn(string maDoAn)
    {
        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_DoAn_ThanhPhanDoAn_Result>("select_DoAn_ThanhPhanDoAn", maDoAnParameter);
    }

    public virtual ObjectResult<Nullable<decimal>> select_donGia_SanPham(string maSanPham, string donViBan)
    {
        var maSanPhamParameter = maSanPham != null ?
            new ObjectParameter("maSanPham", maSanPham) :
            new ObjectParameter("maSanPham", typeof(string));

        var donViBanParameter = donViBan != null ?
            new ObjectParameter("donViBan", donViBan) :
            new ObjectParameter("donViBan", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("select_donGia_SanPham", maSanPhamParameter, donViBanParameter);
    }

    public virtual ObjectResult<string> select_DonViBanDoAn()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_DonViBanDoAn");
    }

    public virtual ObjectResult<string> select_DonViBanNuoc(string maNuoc)
    {
        var maNuocParameter = maNuoc != null ?
            new ObjectParameter("maNuoc", maNuoc) :
            new ObjectParameter("maNuoc", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_DonViBanNuoc", maNuocParameter);
    }

    public virtual ObjectResult<select_dsDoAnTheoLoai_Result> select_dsDoAnTheoLoai(string maLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_dsDoAnTheoLoai_Result>("select_dsDoAnTheoLoai", maLoaiDoAnParameter);
    }

    public virtual ObjectResult<select_DSMatHang_Result> select_DSMatHang()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_DSMatHang_Result>("select_DSMatHang");
    }

    public virtual ObjectResult<select_dsNuocUong_Result> select_dsNuocUong(string maNuoc)
    {
        var maNuocParameter = maNuoc != null ?
            new ObjectParameter("maNuoc", maNuoc) :
            new ObjectParameter("maNuoc", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_dsNuocUong_Result>("select_dsNuocUong", maNuocParameter);
    }

    public virtual ObjectResult<select_KhachHang_Result> select_KhachHang()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_KhachHang_Result>("select_KhachHang");
    }

    public virtual ObjectResult<select_KhuyenMai_Result> select_KhuyenMai()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_KhuyenMai_Result>("select_KhuyenMai");
    }

    public virtual ObjectResult<select_LoaiDoAn_Result> select_LoaiDoAn()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_LoaiDoAn_Result>("select_LoaiDoAn");
    }

    public virtual ObjectResult<select_LoaiKM_Result> select_LoaiKM()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_LoaiKM_Result>("select_LoaiKM");
    }

    public virtual ObjectResult<select_LoaiNhanVien_Result> select_LoaiNhanVien()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_LoaiNhanVien_Result>("select_LoaiNhanVien");
    }

    public virtual ObjectResult<select_MatHang_DoAn_Result> select_MatHang_DoAn()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_MatHang_DoAn_Result>("select_MatHang_DoAn");
    }

    public virtual ObjectResult<string> select_MatHang_NCC(string maHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_MatHang_NCC", maHangParameter);
    }

    public virtual ObjectResult<select_MatHang_Nuoc_Result> select_MatHang_Nuoc()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_MatHang_Nuoc_Result>("select_MatHang_Nuoc");
    }

    public virtual ObjectResult<select_NCC_Result> select_NCC()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_NCC_Result>("select_NCC");
    }

    public virtual ObjectResult<select_NhanVien_Result> select_NhanVien()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_NhanVien_Result>("select_NhanVien");
    }

    public virtual ObjectResult<select_NhapKho_Result> select_NhapKho()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_NhapKho_Result>("select_NhapKho");
    }

    public virtual ObjectResult<select_NuocUong_Result> select_NuocUong()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_NuocUong_Result>("select_NuocUong");
    }

    public virtual ObjectResult<select_PhanQuyen_Result> select_PhanQuyen()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_PhanQuyen_Result>("select_PhanQuyen");
    }

    public virtual ObjectResult<select_PhieuTra_Result> select_PhieuTra()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_PhieuTra_Result>("select_PhieuTra");
    }

    public virtual ObjectResult<Nullable<int>> select_SoLuongDat(string maDat, string maHang)
    {
        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("select_SoLuongDat", maDatParameter, maHangParameter);
    }

    public virtual ObjectResult<select_thongTin_MatHangNuoc_Result> select_thongTin_MatHangNuoc(string maHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_thongTin_MatHangNuoc_Result>("select_thongTin_MatHangNuoc", maHangParameter);
    }

    public virtual ObjectResult<select_ThongTinDatHang_Result> select_ThongTinDatHang(string maDatHang)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ThongTinDatHang_Result>("select_ThongTinDatHang", maDatHangParameter);
    }

    public virtual ObjectResult<select_ThongTinKhuyenMai_Result> select_ThongTinKhuyenMai(string maKhuyenMai)
    {
        var maKhuyenMaiParameter = maKhuyenMai != null ?
            new ObjectParameter("maKhuyenMai", maKhuyenMai) :
            new ObjectParameter("maKhuyenMai", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ThongTinKhuyenMai_Result>("select_ThongTinKhuyenMai", maKhuyenMaiParameter);
    }

    public virtual ObjectResult<select_ThongTinKhuyenMai_DA_Result> select_ThongTinKhuyenMai_DA(string maKhuyenMai)
    {
        var maKhuyenMaiParameter = maKhuyenMai != null ?
            new ObjectParameter("maKhuyenMai", maKhuyenMai) :
            new ObjectParameter("maKhuyenMai", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ThongTinKhuyenMai_DA_Result>("select_ThongTinKhuyenMai_DA", maKhuyenMaiParameter);
    }

    public virtual ObjectResult<select_ThongTinNhapKho_Result> select_ThongTinNhapKho(string maNhap)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ThongTinNhapKho_Result>("select_ThongTinNhapKho", maNhapParameter);
    }

    public virtual ObjectResult<select_ThongTinPhieuTra_Result> select_ThongTinPhieuTra(string maTra)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_ThongTinPhieuTra_Result>("select_ThongTinPhieuTra", maTraParameter);
    }

    public virtual ObjectResult<select_TKNV_Result> select_TKNV()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_TKNV_Result>("select_TKNV");
    }

    public virtual ObjectResult<select_to_PhieuNhapTemp_Result> select_to_PhieuNhapTemp(string maDat, string maTra)
    {
        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_to_PhieuNhapTemp_Result>("select_to_PhieuNhapTemp", maDatParameter, maTraParameter);
    }

    public virtual ObjectResult<Nullable<decimal>> select_TongGiaNhap(string maNhap)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("select_TongGiaNhap", maNhapParameter);
    }

    public virtual ObjectResult<select_TonKho_Result> select_TonKho()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_TonKho_Result>("select_TonKho");
    }

    public virtual ObjectResult<select_TTSP_Result> select_TTSP()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_TTSP_Result>("select_TTSP");
    }

    public virtual ObjectResult<show_dsDoAn_Result> show_dsDoAn()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<show_dsDoAn_Result>("show_dsDoAn");
    }

    public virtual ObjectResult<Nullable<int>> soLuong_TraHang(string maTra, string maHang)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("soLuong_TraHang", maTraParameter, maHangParameter);
    }

    public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
    }

    public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
    }

    public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
    }

    public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var new_diagramnameParameter = new_diagramname != null ?
            new ObjectParameter("new_diagramname", new_diagramname) :
            new ObjectParameter("new_diagramname", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
    }

    public virtual int sp_upgraddiagrams()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
    }

    public virtual ObjectResult<Nullable<decimal>> tongGia_DatHang(string maDatHang)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("tongGia_DatHang", maDatHangParameter);
    }

    public virtual ObjectResult<Nullable<decimal>> tongGia_TraHang(string maTra)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("tongGia_TraHang", maTraParameter);
    }

    public virtual int update_DatHang(string maDH, Nullable<System.DateTime> ngayDat, Nullable<System.DateTime> ngaydukiengiao, string ghiChu, string phuongthucthanhtoan, Nullable<bool> trangThai)
    {
        var maDHParameter = maDH != null ?
            new ObjectParameter("maDH", maDH) :
            new ObjectParameter("maDH", typeof(string));

        var ngayDatParameter = ngayDat.HasValue ?
            new ObjectParameter("ngayDat", ngayDat) :
            new ObjectParameter("ngayDat", typeof(System.DateTime));

        var ngaydukiengiaoParameter = ngaydukiengiao.HasValue ?
            new ObjectParameter("ngaydukiengiao", ngaydukiengiao) :
            new ObjectParameter("ngaydukiengiao", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var phuongthucthanhtoanParameter = phuongthucthanhtoan != null ?
            new ObjectParameter("phuongthucthanhtoan", phuongthucthanhtoan) :
            new ObjectParameter("phuongthucthanhtoan", typeof(string));

        var trangThaiParameter = trangThai.HasValue ?
            new ObjectParameter("trangThai", trangThai) :
            new ObjectParameter("trangThai", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_DatHang", maDHParameter, ngayDatParameter, ngaydukiengiaoParameter, ghiChuParameter, phuongthucthanhtoanParameter, trangThaiParameter);
    }

    public virtual int update_DoAn_ThanhPhanDoAn(string maThanhPhan, string dinhLuong, string maDoAn, Nullable<int> soLuong)
    {
        var maThanhPhanParameter = maThanhPhan != null ?
            new ObjectParameter("maThanhPhan", maThanhPhan) :
            new ObjectParameter("maThanhPhan", typeof(string));

        var dinhLuongParameter = dinhLuong != null ?
            new ObjectParameter("dinhLuong", dinhLuong) :
            new ObjectParameter("dinhLuong", typeof(string));

        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        var soLuongParameter = soLuong.HasValue ?
            new ObjectParameter("soLuong", soLuong) :
            new ObjectParameter("soLuong", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_DoAn_ThanhPhanDoAn", maThanhPhanParameter, dinhLuongParameter, maDoAnParameter, soLuongParameter);
    }

    public virtual int update_DoAn_ThongTinDoAn(string maDoAn, string maLoaiDoAn, string tenDoAn, string donViBan, Nullable<decimal> donGia, string ghiChu)
    {
        var maDoAnParameter = maDoAn != null ?
            new ObjectParameter("maDoAn", maDoAn) :
            new ObjectParameter("maDoAn", typeof(string));

        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        var tenDoAnParameter = tenDoAn != null ?
            new ObjectParameter("tenDoAn", tenDoAn) :
            new ObjectParameter("tenDoAn", typeof(string));

        var donViBanParameter = donViBan != null ?
            new ObjectParameter("donViBan", donViBan) :
            new ObjectParameter("donViBan", typeof(string));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_DoAn_ThongTinDoAn", maDoAnParameter, maLoaiDoAnParameter, tenDoAnParameter, donViBanParameter, donGiaParameter, ghiChuParameter);
    }

    public virtual int update_KhachHang(string tenKhachHang, string phai, string sDT, string email, string diaChi, string ghiChu, Nullable<int> idKhachHang)
    {
        var tenKhachHangParameter = tenKhachHang != null ?
            new ObjectParameter("tenKhachHang", tenKhachHang) :
            new ObjectParameter("tenKhachHang", typeof(string));

        var phaiParameter = phai != null ?
            new ObjectParameter("Phai", phai) :
            new ObjectParameter("Phai", typeof(string));

        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));

        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));

        var diaChiParameter = diaChi != null ?
            new ObjectParameter("diaChi", diaChi) :
            new ObjectParameter("diaChi", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var idKhachHangParameter = idKhachHang.HasValue ?
            new ObjectParameter("idKhachHang", idKhachHang) :
            new ObjectParameter("idKhachHang", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_KhachHang", tenKhachHangParameter, phaiParameter, sDTParameter, emailParameter, diaChiParameter, ghiChuParameter, idKhachHangParameter);
    }

    public virtual int update_KM(string maKM, string tenKM, string maLoaiKM, Nullable<double> mucGiam)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        var tenKMParameter = tenKM != null ?
            new ObjectParameter("tenKM", tenKM) :
            new ObjectParameter("tenKM", typeof(string));

        var maLoaiKMParameter = maLoaiKM != null ?
            new ObjectParameter("maLoaiKM", maLoaiKM) :
            new ObjectParameter("maLoaiKM", typeof(string));

        var mucGiamParameter = mucGiam.HasValue ?
            new ObjectParameter("mucGiam", mucGiam) :
            new ObjectParameter("mucGiam", typeof(double));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_KM", maKMParameter, tenKMParameter, maLoaiKMParameter, mucGiamParameter);
    }

    public virtual int update_LoaiDoAn(string maLoaiDoAn, string tenLoaiDoAn)
    {
        var maLoaiDoAnParameter = maLoaiDoAn != null ?
            new ObjectParameter("maLoaiDoAn", maLoaiDoAn) :
            new ObjectParameter("maLoaiDoAn", typeof(string));

        var tenLoaiDoAnParameter = tenLoaiDoAn != null ?
            new ObjectParameter("tenLoaiDoAn", tenLoaiDoAn) :
            new ObjectParameter("tenLoaiDoAn", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_LoaiDoAn", maLoaiDoAnParameter, tenLoaiDoAnParameter);
    }

    public virtual int update_LoaiKM(string maLoai, string tenLoai)
    {
        var maLoaiParameter = maLoai != null ?
            new ObjectParameter("maLoai", maLoai) :
            new ObjectParameter("maLoai", typeof(string));

        var tenLoaiParameter = tenLoai != null ?
            new ObjectParameter("tenLoai", tenLoai) :
            new ObjectParameter("tenLoai", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_LoaiKM", maLoaiParameter, tenLoaiParameter);
    }

    public virtual int update_MatHang(string maHang, string tenHang, string maNCC, string donVi, Nullable<System.DateTime> nSX, Nullable<System.DateTime> hSD, Nullable<decimal> donGia, string ghiChu, Nullable<bool> loaiHang)
    {
        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var tenHangParameter = tenHang != null ?
            new ObjectParameter("tenHang", tenHang) :
            new ObjectParameter("tenHang", typeof(string));

        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        var donViParameter = donVi != null ?
            new ObjectParameter("donVi", donVi) :
            new ObjectParameter("donVi", typeof(string));

        var nSXParameter = nSX.HasValue ?
            new ObjectParameter("NSX", nSX) :
            new ObjectParameter("NSX", typeof(System.DateTime));

        var hSDParameter = hSD.HasValue ?
            new ObjectParameter("HSD", hSD) :
            new ObjectParameter("HSD", typeof(System.DateTime));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var loaiHangParameter = loaiHang.HasValue ?
            new ObjectParameter("loaiHang", loaiHang) :
            new ObjectParameter("loaiHang", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_MatHang", maHangParameter, tenHangParameter, maNCCParameter, donViParameter, nSXParameter, hSDParameter, donGiaParameter, ghiChuParameter, loaiHangParameter);
    }

    public virtual int update_NhanVien(string maNhanVien, string tenNhanVien, string phai, string sDT, string email, string diaChi, string maChucDanh, string maLoaiNhanVien)
    {
        var maNhanVienParameter = maNhanVien != null ?
            new ObjectParameter("maNhanVien", maNhanVien) :
            new ObjectParameter("maNhanVien", typeof(string));

        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("tenNhanVien", tenNhanVien) :
            new ObjectParameter("tenNhanVien", typeof(string));

        var phaiParameter = phai != null ?
            new ObjectParameter("Phai", phai) :
            new ObjectParameter("Phai", typeof(string));

        var sDTParameter = sDT != null ?
            new ObjectParameter("SDT", sDT) :
            new ObjectParameter("SDT", typeof(string));

        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));

        var diaChiParameter = diaChi != null ?
            new ObjectParameter("diaChi", diaChi) :
            new ObjectParameter("diaChi", typeof(string));

        var maChucDanhParameter = maChucDanh != null ?
            new ObjectParameter("maChucDanh", maChucDanh) :
            new ObjectParameter("maChucDanh", typeof(string));

        var maLoaiNhanVienParameter = maLoaiNhanVien != null ?
            new ObjectParameter("maLoaiNhanVien", maLoaiNhanVien) :
            new ObjectParameter("maLoaiNhanVien", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_NhanVien", maNhanVienParameter, tenNhanVienParameter, phaiParameter, sDTParameter, emailParameter, diaChiParameter, maChucDanhParameter, maLoaiNhanVienParameter);
    }

    public virtual int update_PhieuNhap(string maNhap, Nullable<System.DateTime> ngayNhap, string maDatHang, string ghiChu, Nullable<bool> trangThai)
    {
        var maNhapParameter = maNhap != null ?
            new ObjectParameter("maNhap", maNhap) :
            new ObjectParameter("maNhap", typeof(string));

        var ngayNhapParameter = ngayNhap.HasValue ?
            new ObjectParameter("ngayNhap", ngayNhap) :
            new ObjectParameter("ngayNhap", typeof(System.DateTime));

        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var trangThaiParameter = trangThai.HasValue ?
            new ObjectParameter("trangThai", trangThai) :
            new ObjectParameter("trangThai", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_PhieuNhap", maNhapParameter, ngayNhapParameter, maDatHangParameter, ghiChuParameter, trangThaiParameter);
    }

    public virtual int update_Quyen(string maQuyen, string tenQuyen, string ghiChu)
    {
        var maQuyenParameter = maQuyen != null ?
            new ObjectParameter("maQuyen", maQuyen) :
            new ObjectParameter("maQuyen", typeof(string));

        var tenQuyenParameter = tenQuyen != null ?
            new ObjectParameter("tenQuyen", tenQuyen) :
            new ObjectParameter("tenQuyen", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Quyen", maQuyenParameter, tenQuyenParameter, ghiChuParameter);
    }

    public virtual int update_QuyenTKNV(Nullable<int> id, string maQuyen)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var maQuyenParameter = maQuyen != null ?
            new ObjectParameter("maQuyen", maQuyen) :
            new ObjectParameter("maQuyen", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_QuyenTKNV", idParameter, maQuyenParameter);
    }

    public virtual int update_ThongTinDatHang(string maDatHang, string maHang, Nullable<int> soLuongDat)
    {
        var maDatHangParameter = maDatHang != null ?
            new ObjectParameter("maDatHang", maDatHang) :
            new ObjectParameter("maDatHang", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var soLuongDatParameter = soLuongDat.HasValue ?
            new ObjectParameter("soLuongDat", soLuongDat) :
            new ObjectParameter("soLuongDat", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_ThongTinDatHang", maDatHangParameter, maHangParameter, soLuongDatParameter);
    }

    public virtual int update_ThongTinKhuyenMai(string maKM, string maSP, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, string ghiChu)
    {
        var maKMParameter = maKM != null ?
            new ObjectParameter("maKM", maKM) :
            new ObjectParameter("maKM", typeof(string));

        var maSPParameter = maSP != null ?
            new ObjectParameter("maSP", maSP) :
            new ObjectParameter("maSP", typeof(string));

        var ngayBDParameter = ngayBD.HasValue ?
            new ObjectParameter("ngayBD", ngayBD) :
            new ObjectParameter("ngayBD", typeof(System.DateTime));

        var ngayKTParameter = ngayKT.HasValue ?
            new ObjectParameter("ngayKT", ngayKT) :
            new ObjectParameter("ngayKT", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_ThongTinKhuyenMai", maKMParameter, maSPParameter, ngayBDParameter, ngayKTParameter, ghiChuParameter);
    }

    public virtual int update_ThongTinTraHang(string maTra, string maHang, Nullable<int> soLuongTra)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var maHangParameter = maHang != null ?
            new ObjectParameter("maHang", maHang) :
            new ObjectParameter("maHang", typeof(string));

        var soLuongTraParameter = soLuongTra.HasValue ?
            new ObjectParameter("soLuongTra", soLuongTra) :
            new ObjectParameter("soLuongTra", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_ThongTinTraHang", maTraParameter, maHangParameter, soLuongTraParameter);
    }

    public virtual int update_to_NCC(string maNCC, string tenNCC, string diachiNCC, string emailNCC, string sdtNCC, string ghiChu)
    {
        var maNCCParameter = maNCC != null ?
            new ObjectParameter("maNCC", maNCC) :
            new ObjectParameter("maNCC", typeof(string));

        var tenNCCParameter = tenNCC != null ?
            new ObjectParameter("tenNCC", tenNCC) :
            new ObjectParameter("tenNCC", typeof(string));

        var diachiNCCParameter = diachiNCC != null ?
            new ObjectParameter("diachiNCC", diachiNCC) :
            new ObjectParameter("diachiNCC", typeof(string));

        var emailNCCParameter = emailNCC != null ?
            new ObjectParameter("emailNCC", emailNCC) :
            new ObjectParameter("emailNCC", typeof(string));

        var sdtNCCParameter = sdtNCC != null ?
            new ObjectParameter("sdtNCC", sdtNCC) :
            new ObjectParameter("sdtNCC", typeof(string));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_to_NCC", maNCCParameter, tenNCCParameter, diachiNCCParameter, emailNCCParameter, sdtNCCParameter, ghiChuParameter);
    }

    public virtual int update_to_NuocUong(string maNuocUong, string tenNuocUong, string donViBan, Nullable<decimal> donGia)
    {
        var maNuocUongParameter = maNuocUong != null ?
            new ObjectParameter("maNuocUong", maNuocUong) :
            new ObjectParameter("maNuocUong", typeof(string));

        var tenNuocUongParameter = tenNuocUong != null ?
            new ObjectParameter("tenNuocUong", tenNuocUong) :
            new ObjectParameter("tenNuocUong", typeof(string));

        var donViBanParameter = donViBan != null ?
            new ObjectParameter("donViBan", donViBan) :
            new ObjectParameter("donViBan", typeof(string));

        var donGiaParameter = donGia.HasValue ?
            new ObjectParameter("donGia", donGia) :
            new ObjectParameter("donGia", typeof(decimal));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_to_NuocUong", maNuocUongParameter, tenNuocUongParameter, donViBanParameter, donGiaParameter);
    }

    public virtual int update_TraHang(string maTra, Nullable<System.DateTime> ngayTra, string ghiChu, string maDat)
    {
        var maTraParameter = maTra != null ?
            new ObjectParameter("maTra", maTra) :
            new ObjectParameter("maTra", typeof(string));

        var ngayTraParameter = ngayTra.HasValue ?
            new ObjectParameter("ngayTra", ngayTra) :
            new ObjectParameter("ngayTra", typeof(System.DateTime));

        var ghiChuParameter = ghiChu != null ?
            new ObjectParameter("ghiChu", ghiChu) :
            new ObjectParameter("ghiChu", typeof(string));

        var maDatParameter = maDat != null ?
            new ObjectParameter("maDat", maDat) :
            new ObjectParameter("maDat", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_TraHang", maTraParameter, ngayTraParameter, ghiChuParameter, maDatParameter);
    }
}
