//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CaLam
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CaLam()
    {
        this.ChamCongs = new HashSet<ChamCong>();
    }

    public string maCaLam { get; set; }
    public string tenCaLam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChamCong> ChamCongs { get; set; }
    public virtual ThongTinCaLam ThongTinCaLam { get; set; }
}

public partial class ChamCong
{
    public string maNhanVien { get; set; }
    public Nullable<System.DateTime> ngayLam { get; set; }
    public Nullable<System.TimeSpan> gioVao { get; set; }
    public Nullable<System.TimeSpan> gioRa { get; set; }
    public string maCaLam { get; set; }
    public string ghiChu { get; set; }

    public virtual CaLam CaLam { get; set; }
    public virtual NhanVien NhanVien { get; set; }
}

public partial class ChucDanh
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ChucDanh()
    {
        this.NhanViens = new HashSet<NhanVien>();
    }

    public string maChucDanh { get; set; }
    public string tenChucDanh { get; set; }
    public Nullable<double> heSoLuong { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhanVien> NhanViens { get; set; }
}

public partial class DanhGia
{
    public string maSanPham { get; set; }
    public string thongTinDanhGia { get; set; }
    public int idKhachHang { get; set; }

    public virtual KhachHang KhachHang { get; set; }
    public virtual SanPham SanPham { get; set; }
}

public partial class DatHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DatHang()
    {
        this.NhapKhoes = new HashSet<NhapKho>();
        this.ThongTinDatHangs = new HashSet<ThongTinDatHang>();
        this.TraHangs = new HashSet<TraHang>();
    }

    public string maDatHang { get; set; }
    public Nullable<System.DateTime> ngayDatHang { get; set; }
    public Nullable<System.DateTime> ngayDuKienGiao { get; set; }
    public string ghiChu { get; set; }
    public string phuongThucThanhToan { get; set; }
    public Nullable<bool> trangThai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhapKho> NhapKhoes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinDatHang> ThongTinDatHangs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TraHang> TraHangs { get; set; }
}

public partial class DoAn
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DoAn()
    {
        this.ThongTinThanhPhanDoAns = new HashSet<ThongTinThanhPhanDoAn>();
    }

    public string maDoAn { get; set; }
    public string maLoaiDoAn { get; set; }
    public string tenDoAn { get; set; }

    public virtual SanPham SanPham { get; set; }
    public virtual ThongTinDoAn ThongTinDoAn { get; set; }
    public virtual LoaiDoAn LoaiDoAn { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinThanhPhanDoAn> ThongTinThanhPhanDoAns { get; set; }
}

public partial class DonHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonHang()
    {
        this.ThongTinDonHangs = new HashSet<ThongTinDonHang>();
    }

    public string maDonHang { get; set; }
    public string tenDonHang { get; set; }
    public string maLoaiDon { get; set; }
    public Nullable<bool> maHinhthuc { get; set; }
    public string maNhanVien { get; set; }
    public string SDTKhachHang { get; set; }
    public string maKhuyenMai { get; set; }
    public Nullable<System.DateTime> thoiGianDat { get; set; }
    public Nullable<int> trangThai { get; set; }
    public string ghiChu { get; set; }
    public Nullable<int> idKhachHang { get; set; }
    public Nullable<decimal> tongGia { get; set; }

    public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
    public virtual KhuyenMai KhuyenMai { get; set; }
    public virtual LoaiDonHang LoaiDonHang { get; set; }
    public virtual NhanVien NhanVien { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinDonHang> ThongTinDonHangs { get; set; }
}

public partial class HinhThucThanhToan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HinhThucThanhToan()
    {
        this.DonHangs = new HashSet<DonHang>();
    }

    public bool maHinhThuc { get; set; }
    public string tenHinhThuc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DonHang> DonHangs { get; set; }
}

public partial class KhachHang
{
    public string tenKhachHang { get; set; }
    public string Phai { get; set; }
    public string SDT { get; set; }
    public string Email { get; set; }
    public string diaChi { get; set; }
    public string ghiChu { get; set; }
    public int idKhachHang { get; set; }

    public virtual DanhGia DanhGia { get; set; }
}

public partial class KhoBan
{
    public string maHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> tongGia { get; set; }
    public string maXuat { get; set; }

    public virtual MatHang MatHang { get; set; }
    public virtual XuatKho XuatKho { get; set; }
}

public partial class KhuyenMai
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhuyenMai()
    {
        this.DonHangs = new HashSet<DonHang>();
        this.ThongTinKhuyenMais = new HashSet<ThongTinKhuyenMai>();
    }

    public string maKhuyenMai { get; set; }
    public string tenKhuyenMai { get; set; }
    public string maLoaiKhuyenMai { get; set; }
    public Nullable<double> mucGiam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DonHang> DonHangs { get; set; }
    public virtual LoaiKhuyenMai LoaiKhuyenMai { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
}

public partial class LoaiDoAn
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiDoAn()
    {
        this.DoAns = new HashSet<DoAn>();
    }

    public string maLoaiDoAn { get; set; }
    public string tenLoaiDoAn { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DoAn> DoAns { get; set; }
}

public partial class LoaiDonHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiDonHang()
    {
        this.DonHangs = new HashSet<DonHang>();
    }

    public string maLoaiDon { get; set; }
    public string tenLoaiDon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DonHang> DonHangs { get; set; }
}

public partial class LoaiKhuyenMai
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiKhuyenMai()
    {
        this.KhuyenMais = new HashSet<KhuyenMai>();
    }

    public string maLoaiKhuyenMai { get; set; }
    public string tenLoaiKhuyenMai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
}

public partial class LoaiNhanVien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiNhanVien()
    {
        this.NhanViens = new HashSet<NhanVien>();
    }

    public string maLoaiNhanVien { get; set; }
    public string tenLoaiNhanVien { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhanVien> NhanViens { get; set; }
}

public partial class LoaiSanPham
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiSanPham()
    {
        this.SanPhams = new HashSet<SanPham>();
    }

    public string maLoaiSanPham { get; set; }
    public string tenLoaiSanPham { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SanPham> SanPhams { get; set; }
}

public partial class MatHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MatHang()
    {
        this.KhoBans = new HashSet<KhoBan>();
        this.ThongTinDatHangs = new HashSet<ThongTinDatHang>();
        this.ThongTinNhapKhoes = new HashSet<ThongTinNhapKho>();
        this.ThongTinThanhPhanDoAns = new HashSet<ThongTinThanhPhanDoAn>();
        this.ThongTinTraHangs = new HashSet<ThongTinTraHang>();
        this.ThongTinXuatKhoes = new HashSet<ThongTinXuatKho>();
    }

    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string donVi { get; set; }
    public Nullable<System.DateTime> NSX { get; set; }
    public Nullable<System.DateTime> HSD { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> loaiHang { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<KhoBan> KhoBans { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
    public virtual NuocUong NuocUong { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinDatHang> ThongTinDatHangs { get; set; }
    public virtual ThongTinHangTon ThongTinHangTon { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinNhapKho> ThongTinNhapKhoes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinThanhPhanDoAn> ThongTinThanhPhanDoAns { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinTraHang> ThongTinTraHangs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinXuatKho> ThongTinXuatKhoes { get; set; }
}

public partial class NhaCungCap
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhaCungCap()
    {
        this.MatHangs = new HashSet<MatHang>();
        this.ThongTinNhapKhoes = new HashSet<ThongTinNhapKho>();
        this.ThongTinDatHangs = new HashSet<ThongTinDatHang>();
        this.ThongTinTraHangs = new HashSet<ThongTinTraHang>();
    }

    public string maNCC { get; set; }
    public string tenNCC { get; set; }
    public string diaChiNCC { get; set; }
    public string emailNCC { get; set; }
    public string sdtNCC { get; set; }
    public string ghiChu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MatHang> MatHangs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinNhapKho> ThongTinNhapKhoes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinDatHang> ThongTinDatHangs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinTraHang> ThongTinTraHangs { get; set; }
}

public partial class NhanVien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhanVien()
    {
        this.DonHangs = new HashSet<DonHang>();
        this.TaiKhoanNhanViens = new HashSet<TaiKhoanNhanVien>();
        this.ThongTinPhucLois = new HashSet<ThongTinPhucLoi>();
        this.ThongTinViPhams = new HashSet<ThongTinViPham>();
    }

    public string maNhanVien { get; set; }
    public string tenNhanVien { get; set; }
    public string Phai { get; set; }
    public string SDT { get; set; }
    public string Email { get; set; }
    public string diaChi { get; set; }
    public string maChucDanh { get; set; }
    public string maLoaiNhanVien { get; set; }

    public virtual ChamCong ChamCong { get; set; }
    public virtual ChucDanh ChucDanh { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DonHang> DonHangs { get; set; }
    public virtual LoaiNhanVien LoaiNhanVien { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TaiKhoanNhanVien> TaiKhoanNhanViens { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinPhucLoi> ThongTinPhucLois { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinViPham> ThongTinViPhams { get; set; }
}

public partial class NhapKho
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhapKho()
    {
        this.ThongTinNhapKhoes = new HashSet<ThongTinNhapKho>();
    }

    public string maNhap { get; set; }
    public Nullable<System.DateTime> ngayNhap { get; set; }
    public string maDatHang { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> trangThai { get; set; }

    public virtual DatHang DatHang { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinNhapKho> ThongTinNhapKhoes { get; set; }
}

public partial class NuocUong
{
    public string maNuoc { get; set; }
    public string tenNuoc { get; set; }
    public string donViBan { get; set; }
    public Nullable<decimal> giaBanNuoc { get; set; }

    public virtual MatHang MatHang { get; set; }
    public virtual SanPham SanPham { get; set; }
}

public partial class PhanQuyen
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhanQuyen()
    {
        this.TaiKhoanNhanViens = new HashSet<TaiKhoanNhanVien>();
    }

    public string maQuyen { get; set; }
    public string tenQuyen { get; set; }
    public string ghiChu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TaiKhoanNhanVien> TaiKhoanNhanViens { get; set; }
}

public partial class PhucLoi
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhucLoi()
    {
        this.ThongTinPhucLois = new HashSet<ThongTinPhucLoi>();
    }

    public string maPhucLoi { get; set; }
    public string tenPhucLoi { get; set; }
    public Nullable<decimal> mucThuong { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinPhucLoi> ThongTinPhucLois { get; set; }
}

public partial class SanPham
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPham()
    {
        this.DanhGias = new HashSet<DanhGia>();
        this.ThongTinDonHangs = new HashSet<ThongTinDonHang>();
        this.ThongTinKhuyenMais = new HashSet<ThongTinKhuyenMai>();
    }

    public string maSanPham { get; set; }
    public string maLoaiSanPham { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DanhGia> DanhGias { get; set; }
    public virtual DoAn DoAn { get; set; }
    public virtual LoaiSanPham LoaiSanPham { get; set; }
    public virtual NuocUong NuocUong { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinDonHang> ThongTinDonHangs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
}

public partial class TaiKhoanNhanVien
{
    public int id { get; set; }
    public string tenTaiKhoan { get; set; }
    public string matKhau { get; set; }
    public string maNhanVien { get; set; }
    public string maQuyen { get; set; }

    public virtual NhanVien NhanVien { get; set; }
    public virtual PhanQuyen PhanQuyen { get; set; }
}

public partial class ThongTinCaLam
{
    public string maCaLam { get; set; }
    public Nullable<System.TimeSpan> gioVao { get; set; }
    public Nullable<System.TimeSpan> gioRa { get; set; }
    public Nullable<int> soLuongNhanVien { get; set; }

    public virtual CaLam CaLam { get; set; }
}

public partial class ThongTinDatHang
{
    public string maDatHang { get; set; }
    public string maHang { get; set; }
    public string maNCC { get; set; }
    public Nullable<int> soLuongDat { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }

    public virtual DatHang DatHang { get; set; }
    public virtual MatHang MatHang { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
}

public partial class ThongTinDoAn
{
    public string maDoAn { get; set; }
    public string donViBan { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }

    public virtual DoAn DoAn { get; set; }
}

public partial class ThongTinDonHang
{
    public string maDonHang { get; set; }
    public string maSanPham { get; set; }
    public Nullable<decimal> giaTien { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> thanhTien { get; set; }

    public virtual DonHang DonHang { get; set; }
    public virtual SanPham SanPham { get; set; }
}

public partial class ThongTinHangTon
{
    public string maHang { get; set; }
    public Nullable<int> soLuongTon { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }

    public virtual MatHang MatHang { get; set; }
}

public partial class ThongTinKhuyenMai
{
    public string maKhuyenMai { get; set; }
    public string maSanPham { get; set; }
    public Nullable<System.DateTime> ngayBatDau { get; set; }
    public Nullable<System.DateTime> ngayKetThuc { get; set; }
    public string ghiChu { get; set; }

    public virtual KhuyenMai KhuyenMai { get; set; }
    public virtual SanPham SanPham { get; set; }
}

public partial class ThongTinNhapKho
{
    public string maNhap { get; set; }
    public string maNCC { get; set; }
    public string maHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }

    public virtual MatHang MatHang { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
    public virtual NhapKho NhapKho { get; set; }
}

public partial class ThongTinPhucLoi
{
    public string maPhucLoi { get; set; }
    public string maNhanVien { get; set; }
    public Nullable<System.DateTime> ngayBatDau { get; set; }
    public Nullable<System.DateTime> ngayKetThuc { get; set; }
    public string ghiChu { get; set; }

    public virtual NhanVien NhanVien { get; set; }
    public virtual PhucLoi PhucLoi { get; set; }
}

public partial class ThongTinThanhPhanDoAn
{
    public string maThanhPhan { get; set; }
    public string tenThanhPhan { get; set; }
    public string dinhLuong { get; set; }
    public string maDoAn { get; set; }
    public Nullable<int> soLuong { get; set; }

    public virtual DoAn DoAn { get; set; }
    public virtual MatHang MatHang { get; set; }
}

public partial class ThongTinTraHang
{
    public string maTra { get; set; }
    public string maNCC { get; set; }
    public string maHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }

    public virtual MatHang MatHang { get; set; }
    public virtual NhaCungCap NhaCungCap { get; set; }
    public virtual TraHang TraHang { get; set; }
}

public partial class ThongTinViPham
{
    public string maViPham { get; set; }
    public string maNhanVien { get; set; }
    public string ghiChu { get; set; }

    public virtual NhanVien NhanVien { get; set; }
    public virtual ViPham ViPham { get; set; }
}

public partial class ThongTinXuatKho
{
    public string maXuat { get; set; }
    public string maHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public string ghiChu { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }

    public virtual MatHang MatHang { get; set; }
    public virtual XuatKho XuatKho { get; set; }
}

public partial class TraHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TraHang()
    {
        this.ThongTinTraHangs = new HashSet<ThongTinTraHang>();
    }

    public string maTra { get; set; }
    public Nullable<System.DateTime> ngayTra { get; set; }
    public string ghiChu { get; set; }
    public string maDatHang { get; set; }
    public Nullable<bool> trangThai { get; set; }

    public virtual DatHang DatHang { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinTraHang> ThongTinTraHangs { get; set; }
}

public partial class ViPham
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ViPham()
    {
        this.ThongTinViPhams = new HashSet<ThongTinViPham>();
    }

    public string maViPham { get; set; }
    public string tenViPham { get; set; }
    public Nullable<decimal> mucPhat { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinViPham> ThongTinViPhams { get; set; }
}

public partial class XuatKho
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public XuatKho()
    {
        this.KhoBans = new HashSet<KhoBan>();
        this.ThongTinXuatKhoes = new HashSet<ThongTinXuatKho>();
    }

    public string maXuat { get; set; }
    public Nullable<System.DateTime> ngayXuat { get; set; }
    public Nullable<bool> trangThai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<KhoBan> KhoBans { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinXuatKho> ThongTinXuatKhoes { get; set; }
}

public partial class check_DoAn_LoaiDoAn_Result
{
    public string maDoAn { get; set; }
    public string maLoaiDoAn { get; set; }
    public string tenDoAn { get; set; }
}

public partial class check_MaNhapKho_Result
{
    public string maNhap { get; set; }
    public Nullable<System.DateTime> ngayNhap { get; set; }
    public string maDatHang { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> trangThai { get; set; }
}

public partial class check_MatHang_ThanhPhan_Result
{
    public string maThanhPhan { get; set; }
    public string tenThanhPhan { get; set; }
    public string dinhLuong { get; set; }
    public string maDoAn { get; set; }
    public Nullable<int> soLuong { get; set; }
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string donVi { get; set; }
    public Nullable<System.DateTime> NSX { get; set; }
    public Nullable<System.DateTime> HSD { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> loaiHang { get; set; }
}

public partial class check_PhieuDat_PhieuNhap_Result
{
    public string maNhap { get; set; }
    public Nullable<System.DateTime> ngayNhap { get; set; }
    public string maDatHang { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> trangThai { get; set; }
    public string maDatHang1 { get; set; }
    public Nullable<System.DateTime> ngayDatHang { get; set; }
    public Nullable<System.DateTime> ngayDuKienGiao { get; set; }
    public string ghiChu1 { get; set; }
    public string phuongThucThanhToan { get; set; }
    public Nullable<bool> trangThai1 { get; set; }
}

public partial class check_ThongTinDonHang_KhoBan_Result
{
    public string maHang { get; set; }
    public Nullable<int> soLuong { get; set; }
}

public partial class chect_exist_LoaiDoAn_Result
{
    public string maLoaiDoAn { get; set; }
    public string tenLoaiDoAn { get; set; }
}

public partial class DangNhap_Result
{
    public string tenTaiKhoan { get; set; }
    public string matKhau { get; set; }
    public string maQuyen { get; set; }
}

public partial class find_KhachHang_Result
{
    public string tenKhachHang { get; set; }
    public string Phai { get; set; }
    public string SDT { get; set; }
    public string Email { get; set; }
    public string diaChi { get; set; }
    public string ghiChu { get; set; }
    public int idKhachHang { get; set; }
}

public partial class select_ChucDanh_Result
{
    public string maChucDanh { get; set; }
    public string tenChucDanh { get; set; }
}

public partial class select_DatHang_Result
{
    public string maDatHang { get; set; }
    public Nullable<System.DateTime> ngayDatHang { get; set; }
    public Nullable<System.DateTime> ngayDuKienGiao { get; set; }
    public string ghiChu { get; set; }
    public string phuongThucThanhToan { get; set; }
    public Nullable<bool> trangThai { get; set; }
}

public partial class select_DoAn_ThanhPhanDoAn_Result
{
    public string maThanhPhan { get; set; }
    public string tenThanhPhan { get; set; }
    public string dinhLuong { get; set; }
    public string maDoAn { get; set; }
    public Nullable<int> soLuong { get; set; }
}

public partial class select_dsDoAnTheoLoai_Result
{
    public string tenDoAn { get; set; }
    public string maDoAn { get; set; }
}

public partial class select_DSMatHang_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string donVi { get; set; }
    public Nullable<System.DateTime> NSX { get; set; }
    public Nullable<System.DateTime> HSD { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> loaiHang { get; set; }
}

public partial class select_dsNuocUong_Result
{
    public string tenNuoc { get; set; }
    public string maNuoc { get; set; }
}

public partial class select_KhachHang_Result
{
    public string tenKhachHang { get; set; }
    public string Phai { get; set; }
    public string SDT { get; set; }
    public string Email { get; set; }
    public string diaChi { get; set; }
    public string ghiChu { get; set; }
    public int idKhachHang { get; set; }
}

public partial class select_KhoBan_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> tongGia { get; set; }
}

public partial class select_KhuyenMai_Result
{
    public string maKhuyenMai { get; set; }
    public string tenKhuyenMai { get; set; }
    public string maLoaiKhuyenMai { get; set; }
    public Nullable<double> mucGiam { get; set; }
}

public partial class select_LoaiDoAn_Result
{
    public string maLoaiDoAn { get; set; }
    public string tenLoaiDoAn { get; set; }
}

public partial class select_LoaiKM_Result
{
    public string maLoaiKhuyenMai { get; set; }
    public string tenLoaiKhuyenMai { get; set; }
}

public partial class select_LoaiNhanVien_Result
{
    public string maLoaiNhanVien { get; set; }
    public string tenLoaiNhanVien { get; set; }
}

public partial class select_MatHang_DoAn_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string donVi { get; set; }
    public Nullable<System.DateTime> NSX { get; set; }
    public Nullable<System.DateTime> HSD { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> loaiHang { get; set; }
}

public partial class select_MatHang_Nuoc_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string donVi { get; set; }
    public Nullable<System.DateTime> NSX { get; set; }
    public Nullable<System.DateTime> HSD { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> loaiHang { get; set; }
}

public partial class select_NCC_Result
{
    public string maNCC { get; set; }
    public string tenNCC { get; set; }
    public string diaChiNCC { get; set; }
    public string emailNCC { get; set; }
    public string sdtNCC { get; set; }
    public string ghiChu { get; set; }
}

public partial class select_NhanVien_Result
{
    public string maNhanVien { get; set; }
    public string tenNhanVien { get; set; }
    public string Phai { get; set; }
    public string maChucDanh { get; set; }
    public string tenChucDanh { get; set; }
    public string Email { get; set; }
    public string SDT { get; set; }
    public string diaChi { get; set; }
    public string tenLoaiNhanVien { get; set; }
    public string maLoaiNhanVien { get; set; }
}

public partial class select_NhapKho_Result
{
    public string maNhap { get; set; }
    public Nullable<System.DateTime> ngayNhap { get; set; }
    public string maDatHang { get; set; }
    public string ghiChu { get; set; }
    public Nullable<bool> trangThai { get; set; }
}

public partial class select_NuocUong_Result
{
    public string maNuoc { get; set; }
    public string tenNuoc { get; set; }
    public string donViBan { get; set; }
    public Nullable<decimal> giaBanNuoc { get; set; }
}

public partial class select_PhanQuyen_Result
{
    public string maQuyen { get; set; }
    public string tenQuyen { get; set; }
    public string ghiChu { get; set; }
}

public partial class select_PhieuTra_Result
{
    public string maTra { get; set; }
    public Nullable<System.DateTime> ngayTra { get; set; }
    public string ghiChu { get; set; }
    public string maDatHang { get; set; }
    public Nullable<bool> trangThai { get; set; }
}

public partial class select_thongTin_MatHangNuoc_Result
{
    public string donVi { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string tenHang { get; set; }
}

public partial class select_ThongTinDatHang_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public Nullable<int> soLuongDat { get; set; }
    public string tenNCC { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_ThongTinKhuyenMai_DA_Result
{
    public string maKhuyenMai { get; set; }
    public string maSanPham { get; set; }
    public string tenDoAn { get; set; }
    public Nullable<System.DateTime> ngayBatDau { get; set; }
    public Nullable<System.DateTime> ngayKetThuc { get; set; }
    public string ghiChu { get; set; }
}

public partial class select_ThongTinKhuyenMai_Result
{
    public string maKhuyenMai { get; set; }
    public string maSanPham { get; set; }
    public string TenSanPham { get; set; }
    public Nullable<System.DateTime> ngayBatDau { get; set; }
    public Nullable<System.DateTime> ngayKetThuc { get; set; }
    public string ghiChu { get; set; }
}

public partial class select_ThongTinNhapKho_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public string tenNCC { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_ThongTinPhieuTra_Result
{
    public string maTra { get; set; }
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string tenNCC { get; set; }
    public Nullable<int> soLuong { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_ThongTinPhieuXuat_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public Nullable<int> soLuong { get; set; }
    public string ghiChu { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_TKNV_Result
{
    public int id { get; set; }
    public string tenTaiKhoan { get; set; }
    public string matKhau { get; set; }
    public string maNhanVien { get; set; }
    public string tenNhanVien { get; set; }
    public string maQuyen { get; set; }
}

public partial class select_to_PhieuNhapTemp_Result
{
    public string maHang { get; set; }
    public string maNCC { get; set; }
    public Nullable<int> soLuongNhap { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_TonKho_Result
{
    public string maHang { get; set; }
    public string tenHang { get; set; }
    public string maNCC { get; set; }
    public string tenNCC { get; set; }
    public Nullable<int> soLuongTon { get; set; }
    public Nullable<decimal> tongDonGia { get; set; }
}

public partial class select_TTSP_Result
{
    public string maSanPham { get; set; }
    public string tenSanPham { get; set; }
}

public partial class select_XuatKho_Result
{
    public string maXuat { get; set; }
    public Nullable<System.DateTime> ngayXuat { get; set; }
    public Nullable<bool> trangThai { get; set; }
}

public partial class show_dsDoAn_Result
{
    public string maDoAn { get; set; }
    public string tenDoAn { get; set; }
    public string tenLoaiDoAn { get; set; }
    public string donViBan { get; set; }
    public Nullable<decimal> donGia { get; set; }
    public string ghiChu { get; set; }
}
