//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodOrder_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string tenKhachHang { get; set; }
        public string Phai { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string diaChi { get; set; }
        public string ghiChu { get; set; }
        public int idKhachHang { get; set; }
    
        public virtual DanhGia DanhGia { get; set; }
    }
}
