//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QLCUAHANGTHUCANNHANHEntities444 : DbContext
{
    public QLCUAHANGTHUCANNHANHEntities444()
        : base("name=QLCUAHANGTHUCANNHANHEntities444")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<CaLam> CaLams { get; set; }
    public virtual DbSet<ChamCong> ChamCongs { get; set; }
    public virtual DbSet<ChucDanh> ChucDanhs { get; set; }
    public virtual DbSet<DatHang> DatHangs { get; set; }
    public virtual DbSet<DoAn> DoAns { get; set; }
    public virtual DbSet<DonHang> DonHangs { get; set; }
    public virtual DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
    public virtual DbSet<KhachHang> KhachHangs { get; set; }
    public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
    public virtual DbSet<LoaiDoAn> LoaiDoAns { get; set; }
    public virtual DbSet<LoaiDonHang> LoaiDonHangs { get; set; }
    public virtual DbSet<LoaiHoaDon> LoaiHoaDons { get; set; }
    public virtual DbSet<LoaiKhuyenMai> LoaiKhuyenMais { get; set; }
    public virtual DbSet<LoaiNhanVien> LoaiNhanViens { get; set; }
    public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
    public virtual DbSet<MatHang> MatHangs { get; set; }
    public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
    public virtual DbSet<NhanVien> NhanViens { get; set; }
    public virtual DbSet<NhapKho> NhapKhoes { get; set; }
    public virtual DbSet<NuocUong> NuocUongs { get; set; }
    public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
    public virtual DbSet<PhucLoi> PhucLois { get; set; }
    public virtual DbSet<SanPham> SanPhams { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TaiKhoanNhanVien> TaiKhoanNhanViens { get; set; }
    public virtual DbSet<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
    public virtual DbSet<ThongTinThanhPhanDoAn> ThongTinThanhPhanDoAns { get; set; }
    public virtual DbSet<TraHang> TraHangs { get; set; }
    public virtual DbSet<ViPham> ViPhams { get; set; }
    public virtual DbSet<XuatKho> XuatKhoes { get; set; }
    public virtual DbSet<KhoBan> KhoBans { get; set; }
    public virtual DbSet<ThongTinHangTon> ThongTinHangTons { get; set; }
}
