//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ThongTinDonHangs = new HashSet<ThongTinDonHang>();
        }
    
        public string maDonHang { get; set; }
        public string tenDonHang { get; set; }
        public string maLoaiDon { get; set; }
        public Nullable<bool> maHinhthuc { get; set; }
        public string maNhanVien { get; set; }
        public string SDTKhachHang { get; set; }
        public string maKhuyenMai { get; set; }
        public Nullable<System.DateTime> thoiGianDat { get; set; }
        public Nullable<int> trangThai { get; set; }
        public string ghiChu { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public Nullable<decimal> tongGia { get; set; }
    
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiDonHang LoaiDonHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<ThongTinDonHang> ThongTinDonHangs { get; set; }
    }
}
