//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public KhuyenMai()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.ThongTinKhuyenMais = new HashSet<ThongTinKhuyenMai>();
        }
    
        public string maKhuyenMai { get; set; }
        public string tenKhuyenMai { get; set; }
        public string maLoaiKhuyenMai { get; set; }
        public Nullable<double> mucGiam { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual LoaiKhuyenMai LoaiKhuyenMai { get; set; }
        public virtual ICollection<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
    }
}
