//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDonHang
    {
        public LoaiDonHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public string maLoaiDon { get; set; }
        public string tenLoaiDon { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
