//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhuyenMai
    {
        public LoaiKhuyenMai()
        {
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public string maLoaiKhuyenMai { get; set; }
        public string tenLoaiKhuyenMai { get; set; }
    
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
    }
}
