//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.TaiKhoanNhanViens = new HashSet<TaiKhoanNhanVien>();
            this.ThongTinPhucLois = new HashSet<ThongTinPhucLoi>();
            this.ThongTinViPhams = new HashSet<ThongTinViPham>();
        }
    
        public string maNhanVien { get; set; }
        public string tenNhanVien { get; set; }
        public string Phai { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string diaChi { get; set; }
        public string maChucDanh { get; set; }
        public string maLoaiNhanVien { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
        public virtual ChucDanh ChucDanh { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual LoaiNhanVien LoaiNhanVien { get; set; }
        public virtual ICollection<TaiKhoanNhanVien> TaiKhoanNhanViens { get; set; }
        public virtual ICollection<ThongTinPhucLoi> ThongTinPhucLois { get; set; }
        public virtual ICollection<ThongTinViPham> ThongTinViPhams { get; set; }
    }
}
