//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocUong
    {
        public string maNuoc { get; set; }
        public string tenNuoc { get; set; }
        public string donViBan { get; set; }
        public Nullable<decimal> giaBanNuoc { get; set; }
        public string HinhURL { get; set; }
    
        public virtual MatHang MatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
