//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.GioHangs = new HashSet<GioHang>();
            this.ThongTinDonHangs = new HashSet<ThongTinDonHang>();
            this.ThongTinKhuyenMais = new HashSet<ThongTinKhuyenMai>();
        }
    
        public string maSanPham { get; set; }
        public string maLoaiSanPham { get; set; }
    
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DoAn DoAn { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NuocUong NuocUong { get; set; }
        public virtual ICollection<ThongTinDonHang> ThongTinDonHangs { get; set; }
        public virtual ICollection<ThongTinKhuyenMai> ThongTinKhuyenMais { get; set; }
    }
}
