//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaLam
    {
        public string maCaLam { get; set; }
        public Nullable<System.TimeSpan> gioVao { get; set; }
        public Nullable<System.TimeSpan> gioRa { get; set; }
        public Nullable<int> soLuongNhanVien { get; set; }
    
        public virtual CaLam CaLam { get; set; }
    }
}
