//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDoAn
    {
        public string maDoAn { get; set; }
        public string donViBan { get; set; }
        public Nullable<decimal> donGia { get; set; }
        public string ghiChu { get; set; }
    
        public virtual DoAn DoAn { get; set; }
    }
}
