//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCHTAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatKho
    {
        public XuatKho()
        {
            this.KhoBans = new HashSet<KhoBan>();
            this.ThongTinXuatKhoes = new HashSet<ThongTinXuatKho>();
        }
    
        public string maXuat { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        public virtual ICollection<KhoBan> KhoBans { get; set; }
        public virtual ICollection<ThongTinXuatKho> ThongTinXuatKhoes { get; set; }
    }
}
